//
//  File.swift
//  chipotleDiet
//
//  Created by  admin on 3/2/19.
//  Copyright © 2019  admin. All rights reserved.
//

struct Data {
    let sections = ["SELECT MEAL", "BEANS & RICE", "FILLINGS", "EXTRA FILLINGS", "TOPPINGS", "SIDES", "DRINKS"]
    let items = [
        ["BURRITO", "BOWL", "SALAD", "TACOS"],
        ["WHITE RICE", "BROWN RICE", "BLACK BEANS", "PINTO BEANS"],
        ["BARBACOA", "CARNITAS", "CHICKEN", "SOFRITAS", "STEAK"],
        ["VEGGIES","QUESO"],
        ["TOMATO SALSA","GREEN SALSA","RED SALSA","CORN","SOUR CREAM","CHEESE","GUACAMOLE","LETTUCE"], ["TORTILLA BREAD ON SIDE", "TORTILLA CHIPS", "LARGE CHIPS", "CHIPS & GUACAMOLE", "LARGE CHIPS & GUACAMOLE", "CHIPS & QUESO", "LARGE CHIPS & LARGE QUESO", "CHIPS & TOMATO SALSA", "CHIPS & CORN SALSA", "CHIPS & GREEN SALSA", "CHIPS & RED SALSA", "GUACAMOLE", "LARGE GUACAMOLE", "QUESO", "LARGE QUESO"], ["PEACH ORANGE JUICE", "100% APPLE JUICE", "PINEAPPLE ORANGE BANANA JUICE", "POMEGRANATE CHERRY JUICE", "BLACKBERRY", "CLEMENTINE", "GRAPEFRUIT"]]
    
}
